# Generated by Django 3.0.2 on 2020-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot', models.CharField(choices=[('vn', 'Vietnam'), ('swe', 'Sweden')], max_length=3)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed')], max_length=12)),
            ],
        ),
    ]
